
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  streamlit:
    build: ./app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
